### ISSUE TITLE
EPIC: All Things Service Mesh

### ISSUE THREAD

**Issue by embano1** [vmware-tanzu/thepodlets#93]
Based on a recently performed Twitter poll there seems to be equal interest in discussing the service mesh space. I briefly discussed this with @carlisia and it's such a broad topic that it would be an EPIC with several episodes.

Target audience:

- Developers
- Operators
- DevOps/SREs
- Enterprise or Platform Architects

Possible episodes for the EPIC:

- [ ] Service Mesh - The Basics
- [ ] Envoy - The Hidden Champion in the Service Mesh Landscape
- [ ] API Gateways vs Service Meshs - Competition or better together?

![image](https://user-images.githubusercontent.com/15986659/78032283-0f12c180-7365-11ea-8721-d7cbbba4404c.png)
[Twitter Poll Source](https://twitter.com/embano1/status/1239503516516917249)

**Comment by carlisia** [comment]
We had another epic on the same topic: https://github.com/vmware-tanzu/thepodlets/issues/35
